# Generated by Django 4.1 on 2022-08-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='relacion',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
